[package]
name = "testing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
htmx_server = { path = "../" }
async-std = "1.10"
maud = "0.25.0"

